name: Lint Python Code Snippets

concurrency:
  group: pullrequest-untrusted-pythonlint-${{ github.event.number }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:

jobs:
  python_lint:
    name: Check Python snippets in Markdown files
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Upgrade pip
        run:
          pip install --upgrade pip
      - name: Create virtual environment
        run:
          python3 -m venv env
      - name: Use virtual environment
        run:
          source env/bin/activate
      - name: Install Flake8 Markdown linter
        run:
          pip install flake8-markdown
      - name: Markdown Lint
        run: flake8-markdown "docs/**/*.md"
